import { faker } from '@faker-js/faker'

/**
 * Test data factory for ModelName
 *
 * Generates mock data for testing. Use this to create consistent test data
 * with sensible defaults that can be overridden as needed.
 *
 * @example
 * const user = createMockModelName({ email: 'specific@email.com' })
 */

export interface MockModelName {
  id: string
  name: string
  email: string
  createdAt: Date
  updatedAt: Date
  // Add other fields as needed
}

/**
 * Create a mock ModelName with optional overrides
 */
export function createMockModelName(overrides: Partial<MockModelName> = {}): MockModelName {
  return {
    id: faker.string.uuid(),
    name: faker.person.fullName(),
    email: faker.internet.email(),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    ...overrides
  }
}

/**
 * Create multiple mock ModelNames
 */
export function createMockModelNames(count: number, overrides: Partial<MockModelName> = {}): MockModelName[] {
  return Array.from({ length: count }, () => createMockModelName(overrides))
}

/**
 * Create a mock ModelName for database insertion
 * (excludes fields that are auto-generated by database)
 */
export function createModelNameData(overrides: Partial<Omit<MockModelName, 'id' | 'createdAt' | 'updatedAt'>> = {}) {
  return {
    name: faker.person.fullName(),
    email: faker.internet.email(),
    ...overrides
  }
}

/**
 * Common test scenarios
 */
export const modelNameFixtures = {
  /**
   * Valid ModelName
   */
  valid: createMockModelName({
    name: 'John Doe',
    email: 'john@example.com'
  }),

  /**
   * ModelName with minimal data
   */
  minimal: createMockModelName({
    name: 'User',
    email: 'user@example.com'
  }),

  /**
   * ModelName with long name
   */
  longName: createMockModelName({
    name: 'A'.repeat(100),
    email: 'long@example.com'
  }),

  /**
   * Recently created ModelName
   */
  recent: createMockModelName({
    createdAt: new Date(),
    updatedAt: new Date()
  }),

  /**
   * Old ModelName
   */
  old: createMockModelName({
    createdAt: faker.date.past({ years: 5 }),
    updatedAt: faker.date.past({ years: 1 })
  })
}
